/*
 * TiffTestFrame.java
 *
 * Created on February 17, 2006, 4:41 PM
 */

package edu.mbl.jif.imaging;

import edu.mbl.jif.imaging.TiffMetadataTreeTest;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author  GBH
 */
public class TiffTestFrame extends javax.swing.JFrame {
   JFileChooser              fc;
   /** Creates new form TiffTestFrame */
   public TiffTestFrame() {
      JFrame.setDefaultLookAndFeelDecorated(true);
      JDialog.setDefaultLookAndFeelDecorated(true);
      setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      initComponents();
      fc = new JFileChooser();
      //fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
      //fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jButton1 = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jButton1.setText("Open");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .add(jButton1)
            .addContainerGap(339, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .add(jButton1)
            .addContainerGap(277, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents
   
   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
      // Open file
      
      int returnVal = fc.showOpenDialog(this);
      
      if (returnVal == JFileChooser.APPROVE_OPTION) {
         File file = fc.getSelectedFile();
         System.out.println(file.getPath());
         System.out.println(file.getAbsolutePath());
         TiffMetadataTreeTest.viewMeta(file.getAbsolutePath());
      }
      
   }//GEN-LAST:event_jButton1ActionPerformed
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new TiffTestFrame().setVisible(true);
         }
      });
   }
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   // End of variables declaration//GEN-END:variables
   
}
