/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.mbl.jif.imaging.nav;

/**
 *
 * @author GBH
 */
public class PrefsDialog extends javax.swing.JDialog {

   /**
    * Creates new form PrefsDialog
    */
   ImageNavigator imgNav;
   
   public PrefsDialog(ImageNavigator imgNav, java.awt.Frame parent, boolean modal) {
      super(parent, modal);
      this.imgNav = imgNav;
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT
    * modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jSlider1 = new javax.swing.JSlider();
      panelFilePrefs = new javax.swing.JPanel();
      jLabel4 = new javax.swing.JLabel();
      clearFavsButton = new javax.swing.JButton();
      panelDisplayPrefs = new javax.swing.JPanel();
      jCheckBox1 = new javax.swing.JCheckBox();
      jCheckBox2 = new javax.swing.JCheckBox();
      jCheckBox3 = new javax.swing.JCheckBox();
      jLabel1 = new javax.swing.JLabel();
      jSpinner1 = new javax.swing.JSpinner();
      jPanel2 = new javax.swing.JPanel();
      resetPrefsButton = new javax.swing.JButton();
      imgTypePanel = new javax.swing.JPanel();
      jPanel3 = new javax.swing.JPanel();
      mmCheck = new javax.swing.JCheckBox();
      omeCheck = new javax.swing.JCheckBox();
      tifCheck = new javax.swing.JCheckBox();
      jPanel1 = new javax.swing.JPanel();
      jpgCheck = new javax.swing.JCheckBox();
      gifCheck = new javax.swing.JCheckBox();
      pngCheck = new javax.swing.JCheckBox();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("ImageNavigator Preferences");

      panelFilePrefs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      jLabel4.setText("Make Current Directory the Default");

      clearFavsButton.setText("Clear Favorites");

      javax.swing.GroupLayout panelFilePrefsLayout = new javax.swing.GroupLayout(panelFilePrefs);
      panelFilePrefs.setLayout(panelFilePrefsLayout);
      panelFilePrefsLayout.setHorizontalGroup(
         panelFilePrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelFilePrefsLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelFilePrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel4)
               .addComponent(clearFavsButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      panelFilePrefsLayout.setVerticalGroup(
         panelFilePrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelFilePrefsLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(clearFavsButton)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      panelDisplayPrefs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      jCheckBox1.setText("Metadata, show:");

      jCheckBox2.setText("type");

      jCheckBox3.setText("comment");

      jLabel1.setText("Columns in table view:");

      javax.swing.GroupLayout panelDisplayPrefsLayout = new javax.swing.GroupLayout(panelDisplayPrefs);
      panelDisplayPrefs.setLayout(panelDisplayPrefsLayout);
      panelDisplayPrefsLayout.setHorizontalGroup(
         panelDisplayPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelDisplayPrefsLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelDisplayPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDisplayPrefsLayout.createSequentialGroup()
                  .addComponent(jLabel1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(50, 50, 50)
                  .addComponent(jCheckBox1)
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDisplayPrefsLayout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addGroup(panelDisplayPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jCheckBox3)
                     .addComponent(jCheckBox2))
                  .addGap(68, 68, 68))))
      );
      panelDisplayPrefsLayout.setVerticalGroup(
         panelDisplayPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelDisplayPrefsLayout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(panelDisplayPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jCheckBox1)
               .addComponent(jLabel1)
               .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jCheckBox2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jCheckBox3)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      resetPrefsButton.setText("Reset All Options");
      resetPrefsButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            resetPrefsButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(resetPrefsButton)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap(35, Short.MAX_VALUE)
            .addComponent(resetPrefsButton)
            .addGap(19, 19, 19))
      );

      imgTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Image Types"));

      jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      mmCheck.setText("Micro-Manager Datasets (.tif)");

      omeCheck.setText("OME-Tiff");

      tifCheck.setText("tif");

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap(9, Short.MAX_VALUE)
            .addComponent(tifCheck)
            .addGap(18, 18, 18)
            .addComponent(mmCheck)
            .addGap(18, 18, 18)
            .addComponent(omeCheck)
            .addGap(22, 22, 22))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(mmCheck)
               .addComponent(omeCheck)
               .addComponent(tifCheck)))
      );

      jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      jpgCheck.setText("jpg");

      gifCheck.setText("gif");

      pngCheck.setText("png");
      pngCheck.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            pngCheckActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jpgCheck)
            .addGap(10, 10, 10)
            .addComponent(gifCheck)
            .addGap(18, 18, 18)
            .addComponent(pngCheck)
            .addContainerGap(181, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jpgCheck)
               .addComponent(gifCheck)
               .addComponent(pngCheck)))
      );

      javax.swing.GroupLayout imgTypePanelLayout = new javax.swing.GroupLayout(imgTypePanel);
      imgTypePanel.setLayout(imgTypePanelLayout);
      imgTypePanelLayout.setHorizontalGroup(
         imgTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(imgTypePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(imgTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(90, Short.MAX_VALUE))
      );
      imgTypePanelLayout.setVerticalGroup(
         imgTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(imgTypePanelLayout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(imgTypePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(panelFilePrefs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(panelDisplayPrefs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(23, Short.MAX_VALUE)
            .addComponent(panelFilePrefs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(imgTypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(panelDisplayPrefs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void resetPrefsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPrefsButtonActionPerformed
      
   }//GEN-LAST:event_resetPrefsButtonActionPerformed

   private void pngCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pngCheckActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_pngCheckActionPerformed

   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton clearFavsButton;
   private javax.swing.JCheckBox gifCheck;
   private javax.swing.JPanel imgTypePanel;
   private javax.swing.JCheckBox jCheckBox1;
   private javax.swing.JCheckBox jCheckBox2;
   private javax.swing.JCheckBox jCheckBox3;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JSlider jSlider1;
   private javax.swing.JSpinner jSpinner1;
   private javax.swing.JCheckBox jpgCheck;
   private javax.swing.JCheckBox mmCheck;
   private javax.swing.JCheckBox omeCheck;
   private javax.swing.JPanel panelDisplayPrefs;
   private javax.swing.JPanel panelFilePrefs;
   private javax.swing.JCheckBox pngCheck;
   private javax.swing.JButton resetPrefsButton;
   private javax.swing.JCheckBox tifCheck;
   // End of variables declaration//GEN-END:variables
}
