/*
 * PanelDisplay.java
 *
 * Created on June 1, 2006, 5:21 PM
 */

package edu.mbl.jif.gui.imaging;

/**
 *
 * @author  GBH
 */
public class PanelAdjust extends javax.swing.JPanel {
   
   /** Creates new form PanelDisplay */
   public PanelAdjust() {
      initComponents();
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    buttonEqualize = new javax.swing.JButton();
    buttonContrast = new javax.swing.JButton();
    jSlider1 = new javax.swing.JSlider();
    jSlider2 = new javax.swing.JSlider();
    jButton3 = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    checkMirror = new javax.swing.JCheckBox();
    jLabel1 = new javax.swing.JLabel();

    setBackground(new java.awt.Color(217, 217, 244));

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adjust"));
    jPanel1.setOpaque(false);

    buttonEqualize.setText("Equalize");
    buttonEqualize.setMargin(new java.awt.Insets(2, 4, 2, 4));

    buttonContrast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mbl/jif/gui/imaging/icons/contrast.png"))); // NOI18N
    buttonContrast.setMargin(new java.awt.Insets(2, 4, 2, 4));

    jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
    jSlider1.setOpaque(false);

    jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
    jSlider2.setOpaque(false);

    org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
          .add(buttonContrast, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(buttonEqualize, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jSlider1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jSlider2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel1Layout.createSequentialGroup()
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jPanel1Layout.createSequentialGroup()
            .add(buttonEqualize)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(buttonContrast))
          .add(jSlider2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(jSlider1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mbl/jif/gui/imaging/icons/histogram16.jpg"))); // NOI18N
    jButton3.setText("Histogram");
    jButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mbl/jif/gui/imaging/icons/oscilloscope.png"))); // NOI18N
    jButton1.setText("Measure");
    jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));

    jPanel2.setOpaque(false);

    checkMirror.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
    checkMirror.setText("MirrorImage");
    checkMirror.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    checkMirror.setMargin(new java.awt.Insets(0, 0, 0, 0));
    checkMirror.setOpaque(false);

    org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .add(checkMirror)
        .addContainerGap(17, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel2Layout.createSequentialGroup()
        .add(20, 20, 20)
        .add(checkMirror)
        .addContainerGap(65, Short.MAX_VALUE))
    );

    jLabel1.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
    jLabel1.setText("Display");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
            .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(25, 25, 25)
        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(30, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
              .add(jLabel1)
              .add(15, 15, 15)
              .add(jButton3)
              .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
              .add(jButton1))
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
   
   
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonContrast;
  private javax.swing.JButton buttonEqualize;
  private javax.swing.JCheckBox checkMirror;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JSlider jSlider1;
  private javax.swing.JSlider jSlider2;
  // End of variables declaration//GEN-END:variables
   
}
