/*
 * PanelDisplay.java
 *
 * Created on June 1, 2006, 5:21 PM
 */

package edu.mbl.jif.gui.imaging;

/**
 *
 * @author  GBH
 */
public class PanelAnalyze extends javax.swing.JPanel {
   
   /** Creates new form PanelDisplay */
   public PanelAnalyze() {
      initComponents();
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonHistogram = new javax.swing.JButton();
    buttonMeasure = new javax.swing.JButton();
    buttonLinePlot = new javax.swing.JButton();

    setBackground(new java.awt.Color(217, 217, 244));
    setBorder(javax.swing.BorderFactory.createTitledBorder("Analysis"));

    buttonHistogram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mbl/jif/gui/imaging/icons/histogram16.jpg"))); // NOI18N
    buttonHistogram.setText("Histogram");
    buttonHistogram.setMargin(new java.awt.Insets(2, 2, 2, 2));

    buttonMeasure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mbl/jif/gui/imaging/icons/oscilloscope.png"))); // NOI18N
    buttonMeasure.setText("Measure");
    buttonMeasure.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    buttonMeasure.setMargin(new java.awt.Insets(2, 2, 2, 2));

    buttonLinePlot.setText("LinePlot");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(buttonLinePlot)
          .add(buttonMeasure)
          .add(layout.createSequentialGroup()
            .add(buttonHistogram, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(284, 284, 284))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(buttonHistogram)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(buttonLinePlot)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(buttonMeasure)
        .addContainerGap(55, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
   
   
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonHistogram;
  private javax.swing.JButton buttonLinePlot;
  private javax.swing.JButton buttonMeasure;
  // End of variables declaration//GEN-END:variables
   
}
